### ISSUE TITLE
Database initialization process failed after delay due to failing sqlcmd command

### ISSUE THREAD

**Issue by ivard** [thirdgen88/mssql-docker#11]
In the Docker entrypoint script, a wait has been implemented for the database to be started. This is done by running `/opt/mssql-tools/bin/sqlcmd` every second until either it succeeds or a 60-second startup delay has passed. In the new Docker image the `/opt/mssql-tools/bin/sqlcmd` tool seems to be missing. Due to this, the entrypoint script keeps failing.

The following command is executed in the Docker entrypoint script:
```
$ /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -l 1 -t 1 -b -Q "SELECT 1"
/bin/sh: 1: /opt/mssql-tools/bin/sqlcmd: not found
```

https://github.com/thirdgen88/mssql-docker/blob/main/shared/docker-entrypoint.sh#L113C8-L113C81

It concerns the latest image of `kcollins/mssql:2019-latest`.

**Comment by thirdgen88** [comment]
For some reason, in the upstream `mcr.microsoft.com/mssql/server` image (seems to just be the `2019` tags), they moved the `/opt/mssql-tools` to `/opt/mssql-tools18`, putting it outside of the PATH.

**Comment by ivard** [comment]
The issue above has been resolved now, but it still does not work. The `sqlcmd` script now returns the following error:

```
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : SSL Provider: [error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:self signed certificate].
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : Client unable to establish connection. For solutions related to encryption errors, see https://go.microsoft.com/fwlink/?linkid=2226722.
```

**Comment by thirdgen88** [comment]
Interesting.   I did encounter this during the updates (once I fixed the path issue), and that is what the `-C` flag I added [here](https://github.com/thirdgen88/mssql-docker/pull/12/files#diff-5935ccb077468456fc2f9faa74563edd3743366bf6d9959324e7bc75235f6819R138) should have addressed--adding implicit trust for this loopback usage of `sqlcmd`.  I was able to launch containers from all three images to a healthy state following the update.  Can you share your specific container configuration (i.e. `docker run ...` or other) that you're launching?

**Comment by thirdgen88** [comment]
Ahhh, I see it now.  I had a lingering volume for some of my final test runs w/ #12.  I'll tidy it up.

**Comment by ivard** [comment]
Everything works now. Thanks for your help.
